### ISSUE TITLE
Token Generation

### ISSUE THREAD

**Issue by thejazz15** [AgoraIO-Community/Agora-Rust-SDK#1]
I noticed there are methods for joining/leaving/switching channels and renewing a token.
Is there an easy way to generate a token on the server side using this library? If yes, it would be great if you can point to me an example.

**Comment by YiqingJackieHuang** [comment]
Yes. Actually, for a production environment, Agora recommends you to generate a token on your server by calling `buildTokenWithUid`. Please refer to [Generate a Token](https://docs.agora.io/en/Interactive%20Broadcast/token_server).

For more information on setting up authentication, please refer to [Set up Authentication](https://docs.agora.io/en/Interactive%20Broadcast/token?platform=All%20Platforms#%E9%83%A8%E7%BD%B2-token-generator).

**Comment by thejazz15** [comment]
@YiqingJackieHuang Hey, thanks for the quick response. I'm looking for the same server side implementation in rust. (With code examples of possible)

**Comment by YiqingJackieHuang** [comment]
As mentioned in [Generate a Token](https://docs.agora.io/en/Interactive%20Broadcast/token_server), Agora provides an open-source [AgoraDynamicKey](https://github.com/AgoraIO/Tools/tree/master/DynamicKey/AgoraDynamicKey) repository on GitHub contributed by Agora and some other helpful contributors, while unfortunately, there are no code examples in Rust at this point. 

Thus, your implementation is fairly welcomed. However, if you or your team really need an example for help, please email me (huangyiqing@agora.io) to have a further discussion on your requirement so that our team may provide you with more targeted support. Wish you all the best : )

**Comment by thejazz15** [comment]
Sure, shooting you an email. Thanks :)
